<?php

/** @var \TiagoSampaio\Campaigns\Block\Product\Tags $block */
/** @var \TiagoSampaio\Campaigns\Helper\Tags $helper */

$helper = $block->getData('tagsHelper');

$tags = $helper->getTagsByProductId($block->getProductId());
?>

<?php if(count($tags) > 0): ?>
    <ul class="campaign-tags">
        <?php foreach ($tags as $tag): ?>
            <li>
               <a class="campaign-link" href="<?= $tag->getUrl() ?>"><?= $tag->getTitle() ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
